### PR TITLE
fix an issue in read_hcd

### PR DESCRIPTION
**Pull request by ConorIA**
Related to issue #6

### CODE REVIEW

**Comment by gavinsimpson** [comment]
Was this not working? Do you have an example. I'd prefer to use the **readr** tools if I'm using it to parse the CSV files. I know there is an issue with the `NA` strings but IIRC this has been addressed in one of the packages... Need to check again but having an example would help.

**Comment by gavinsimpson** [comment]
Ah, ignore me I see the example file now in the issue. I'll take a look again at `count_fields`.

**Comment by gavinsimpson** [comment]
@ConorIA Seems like this PR has now pulled in lots of other changes which would need to be broken out into separate PRs.

**Comment by ConorIA** [comment]
Oh shoot! Yes, yesterday I did some merging forgetting that this PR was based on master. Will revert. 

On September 27, 2016 3:31:04 PM EDT, Gavin Simpson notifications@github.com wrote:

> @ConorIA Seems like this PR has now pulled in lots of other changes
> which would need to be broken out into separate PRs.
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/gavinsimpson/canadaHCD/pull/7#issuecomment-249972582

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ConorIA** [comment]
Ok. All the messy merges have been reverted. I've also doubled checked the `readr` arguments and looked at what `tokenizer_csv` can do, but I can't find any solution as simple as changing to `count.fields`.

**Comment by ConorIA** [comment]
Note, another possibility is to use the `fread` function in the `data.table` package as: 

``` r
df <- fread(file, skip = "Date")
```

Of course, this would complicate your 'types' bits, as they are defined by the value of `SKIP`.

EDIT: This isn't really the spot for this question, but I don't want to open an issue. I was wondering why you drop the Year/Month/Day columns. They can be quite useful when we want to aggregate columns for instance.

**Comment by gavinsimpson** [comment]
@ConorIA I drop those as they are derived data from the `"Date"` column and I didn't see the point in having that info duplicated for all users. It's easy to add from the `"Date"` object if a user needs it.

**Comment by gavinsimpson** [comment]
Thanks @ConorIA. Just needed `utils` adding the `Imports:` in `DESCRIPTION`. (The other changes I made just added back in some pointers as to how to fix the code if `count_fields` gets fixed.

**Pull request merged**
